import "./globals.css";
import { SessionProvider } from "./SessionProvider";
import SWRProvider from "./SWRProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head */}
      <head>
        <title>Next 13 Feats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head>
      <body>
        <SWRProvider>
          <SessionProvider>
            <>{children}</>
          </SessionProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
