import "./globals.css";
import { cookies } from "next/headers";
import { getUserCookie } from "@/lib/getUserCookie";
import { SessionProvider } from "./SessionProvider";
import SWRProvider from "./SWRProvider";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUserCookie(cookies());

  return (
    <html lang="en">
      {/* will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head */}
      <head>
        <title>Next 13 Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head>
      <body>
        {user && <pre>From layout: {JSON.stringify(user, null, 2)}</pre>}
        <SWRProvider>
          <SessionProvider>
            <>{children}</>
          </SessionProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
